## JS IND

const sorry = new discord.MessageEmbed()
      .setColor('#ff2f7d')
      .setAuthor(`Play Command`)
      .setThumbnail('https://i.giphy.com/media/Z4ITmGFsXV19C/200w.webp')
      .setDescription('<:redTick:755369523074301991> I am sorry but you need to be in a voice channel to play music!')
      const sorry2 = new discord.MessageEmbed()
      .setColor('#ff2f7d')
      .setAuthor(`Play Command`)
      .setThumbnail('https://i.giphy.com/media/Z4ITmGFsXV19C/200w.webp')
      .setDescription('<:redTick:755369523074301991> I cannot connect to your voice channel, make sure I have the proper permissions!')
      const sorry3 = new discord.MessageEmbed()
      .setColor('#ff2f7d')
      .setAuthor(`Play Command`)
      .setThumbnail('https://i.giphy.com/media/Z4ITmGFsXV19C/200w.webp')
      .setDescription('<:redTick:755369523074301991> I cannot speak in this voice channel, make sure I have the proper permissions!')
      const sorry4 = new discord.MessageEmbed()
      .setColor('#ff2f7d')
      .setAuthor(`Play Command`)
      .setThumbnail('https://i.giphy.com/media/Z4ITmGFsXV19C/200w.webp')
      .setDescription('<:redTick:755369523074301991> You did not poivide want i want to play')
